# CHIANTI

An Atomic Database for Spectroscopic Diagnostics of Astrophysical Plasmas <cite data-cite="1997A&AS..125..149D"> </cite> <cite data-cite="2019ApJS..241...22D"> </cite>.

## ChiantiIonReader

The `ChiantiIonReader` class is a wrapper for the `ChiantiPy` package that interacts directly with the [database files](https://db.chiantidatabase.org/) and as a consequence uses a different notation. It provides information about individual ions.

In [1]:
from carsus.io.chianti_ import ChiantiIonReader

 ChiantiPy version 0.15.0
[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/tools/util.py:362: SyntaxWarning: invalid escape sequence '\p'
  """
 (warnings.py:112)

 found PyQt5 widgets
 using PyQt5 widgets
[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Spectrum.py:16: SyntaxWarning: invalid escape sequence '\m'
  '''
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Spectrum.py:162: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/tools/data.py:1: SyntaxWarning: invalid escape sequence '\m'
  '''
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/tools/data.py:72: UserWarning: klgfb files are not present:
  it will not be possible to use the freeBound continuum method
  warnings.warn('klgfb files are not present: \n  it will not be possible to use the freeBound continuum method')
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/tools/filters.py:75: SyntaxWarning: invalid escape sequence '\p'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/base/_IonTrails.py:81: SyntaxWarning: invalid escape sequence '\D'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Bunch.py:18: SyntaxWarning: invalid escape sequence '\m'
  '''
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Bunch.py:164: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Bunch.py:261: SyntaxWarning: invalid escape sequence '\i'
  ylabel = self.Labels['spectrumYlabel'] + ' ($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Mspectrum.py:18: SyntaxWarning: invalid escape sequence '\m'
  ''' this is the multiprocessing version of spectrum
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Mspectrum.py:145: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/IpyMspectrum.py:106: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:23: SyntaxWarning: invalid escape sequence '\i'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:124: SyntaxWarning: invalid escape sequence '\p'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:160: SyntaxWarning: invalid escape sequence '\l'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:201: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:233: SyntaxWarning: invalid escape sequence '\p'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:272: SyntaxWarning: invalid escape sequence '\s'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:319: SyntaxWarning: invalid escape sequence '\g'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:343: SyntaxWarning: invalid escape sequence '\m'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:371: SyntaxWarning: invalid escape sequence '\m'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:496: SyntaxWarning: invalid escape sequence '\m'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:735: SyntaxWarning: invalid escape sequence '\m'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:991: SyntaxWarning: invalid escape sequence '\m'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:1025: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Continuum.py:1271: SyntaxWarning: invalid escape sequence '\s'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Ion.py:29: SyntaxWarning: invalid escape sequence '\m'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Ion.py:1110: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Ion.py:2769: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Ion.py:2809: SyntaxWarning: invalid escape sequence '\m'
  """
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Ion.py:3153: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/Ion.py:3241: SyntaxWarning: invalid escape sequence '\i'
  ylabel += '($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'
 (warnings.py:112)

[                py.warnings][WARNING] - /home/runner/micromamba/envs/carsus/lib/python3.12/site-packages/ChiantiPy/core/MradLoss.py:21: SyntaxWarning: invalid escape sequence '\m'
  '''
 (warnings.py:112)

In [2]:
h_1 = ChiantiIonReader('h_1')  # H I == Chianti's `he_1` == Carsus's (1,0)

In [3]:
h_1.levels

,energy,energy_theoretical,J,L,spin_multiplicity,label,term,configuration
level_index,,,,,,,,
1,0.000,0.0,0.5,S,2,NaN,1s,2S0.5
2,82258.956,82303.0,0.5,S,2,NaN,2s,2S0.5
3,82258.921,82303.0,0.5,P,2,NaN,2p,2P0.5
4,82259.287,82303.0,1.5,P,2,NaN,2p,2P1.5
5,97492.224,97544.0,0.5,S,2,NaN,3s,2S0.5
6,97492.213,97544.0,0.5,P,2,NaN,3p,2P0.5
7,97492.321,97544.0,1.5,P,2,NaN,3p,2P1.5
8,97492.321,97544.0,1.5,D,2,NaN,3d,2D1.5
9,97492.357,97544.0,2.5,D,2,NaN,3d,2D2.5
10,102823.855,102879.0,0.5,S,2,NaN,4s,2S0.5
11,102823.851,102879.0,0.5,P,2,NaN,4p,2P0.5
12,102823.896,102879.0,1.5,P,2,NaN,4p,2P1.5
13,102823.896,102879.0,1.5,D,2,NaN,4d,2D1.5
14,102823.911,102879.0,2.5,D,2,NaN,4d,2D2.5
15,102823.911,102879.0,2.5,F,2,NaN,4f,2F2.5
16,102823.919,102879.0,3.5,F,2,NaN,4f,2F3.5
17,105291.633,105348.0,0.5,S,2,NaN,5s,2S0.5
18,105291.631,105348.0,0.5,P,2,NaN,5p,2P0.5
19,105291.654,105348.0,1.5,P,2,NaN,5p,2P1.5
20,105291.654,105348.0,1.5,D,2,NaN,5d,2D1.5
21,105291.662,105348.0,2.5,D,2,NaN,5d,2D2.5
22,105291.662,105348.0,2.5,F,2,NaN,5f,2F2.5
23,105291.666,105348.0,3.5,F,2,NaN,5f,2F3.5
24,105291.666,105348.0,3.5,G,2,NaN,5g,2G3.5
25,105291.668,105348.0,4.5,G,2,NaN,5g,2G4.5

See the [API section](https://epassaro.github.io/carsus/api/carsus.io.chianti_.chianti_.html) for more information.

## ChiantiReader

The `ChiantiReader` class mimics the structure of `GFALLReader` and provides `levels`, `lines` and `collisions` tables for the selected ions.

In [4]:
from carsus.io.chianti_ import ChiantiReader

In [5]:
chianti_reader = ChiantiReader('H-He', collisions=True)

In [6]:
chianti_reader.levels

                                          energy    j label method  priority
atomic_number ion_charge level_index
1             0          0                 0.000  0.5   NaN   None        10
                         1             82258.956  0.5   NaN   None        10
                         2             82258.921  0.5   NaN   None        10
                         3             82259.287  1.5   NaN   None        10
                         4             97492.224  0.5   NaN   None        10
...                                          ...  ...   ...    ...       ...
2             1          20           421353.185  2.5   NaN   None        10
                         21           421353.185  2.5   NaN   None        10
                         22           421353.247  3.5   NaN   None        10
                         23           421353.247  3.5   NaN   None        10
                         24           421353.284  4.5   NaN   None        10

[99 rows x 5 columns]

In [7]:
chianti_reader.lines

                                                             energy_upper  \
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                         None
                                           2                         None
                                           3                         None
                                           5                         None
                                           6                         None
...                                                                   ...
2             1          13                18                        None
                                           21                        None
                                           22                        None
                         14                23                        None
                         15                24                        None

                                                             j_upper  \
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                    None
                                           2                    None
                                           3                    None
                                           5                    None
                                           6                    None
...                                                              ...
2             1          13                18                   None
                                           21                   None
                                           22                   None
                         14                23                   None
                         15                24                   None

                                                             energy_lower  \
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                         None
                                           2                         None
                                           3                         None
                                           5                         None
                                           6                         None
...                                                                   ...
2             1          13                18                        None
                                           21                        None
                                           22                        None
                         14                23                        None
                         15                24                        None

                                                             j_lower  \
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                    None
                                           2                    None
                                           3                    None
                                           5                    None
                                           6                    None
...                                                              ...
2             1          13                18                   None
                                           21                   None
                                           22                   None
                         14                23                   None
                         15                24                   None

                                                              wavelength  \
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                    121.5673
                                           2                    121.5674
                                           3                    121.5668
                                           5                    102.5723
                                           6                    102.5722
...                                                                  ...
2             1          13                18                  1012.6626
                                           21                  1012.6499
                                           22                  1012.6436
                         14                23                  1012.6436
                         15                24                  1012.6523

                                                                   gf
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                   0.0000
                                           2                   0.2780
                                           3                   0.5550
                                           5                   0.0527
                                           6                   0.1050
...                                                               ...
2             1          13                18                  0.1669
                                           21                  0.2544
                                           22                  5.0880
                         14                23                  8.0760
                         15                24                 10.4700

[320 rows x 6 columns]

In [8]:
chianti_reader.collisions

                                                                                                   temperatures  \
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                                        [0.0, 0.25, 0.5, 0.75, 1.0]
                                           2                                        [0.0, 0.25, 0.5, 0.75, 1.0]
                                           3                                        [0.0, 0.25, 0.5, 0.75, 1.0]
                                           4                                        [0.0, 0.25, 0.5, 0.75, 1.0]
                                           5                                        [0.0, 0.25, 0.5, 0.75, 1.0]
...                                                                                                         ...
2             1          1                 20                                       [0.0, 0.25, 0.5, 0.75, 1.0]
                                           21                                       [0.0, 0.25, 0.5, 0.75, 1.0]
                                           22                                       [0.0, 0.25, 0.5, 0.75, 1.0]
                                           23                 [0.0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0....
                                           24                 [0.0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0....

                                                                                            collision_strengths  \
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                           [0.2117, 0.3088, 0.3327, 0.3891, 0.5751]
                                           2                            [0.1132, 0.2708, 0.5017, 0.8519, 1.478]
                                           3                              [0.2265, 0.5424, 1.005, 1.706, 2.961]
                                           4                       [0.05993, 0.07305, 0.08102, 0.09175, 0.1226]
                                           5                         [0.03146, 0.05908, 0.09826, 0.1456, 0.237]
...                                                                                                         ...
2             1          1                 20                          [0.1468, 0.1153, 0.1223, 0.1439, 0.2056]
                                           21                       [0.07747, 0.08309, 0.09658, 0.1086, 0.1121]
                                           22                          [0.1031, 0.1106, 0.1286, 0.1445, 0.1491]
                                           23                 [0.04943, 0.03406, 0.02674, 0.02347, 0.02156, ...
                                           24                 [0.06189, 0.04265, 0.03349, 0.02938, 0.02701, ...

                                                                   gf  energy  \
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                  0.00000   0.750
                                           2                  0.27720   0.750
                                           3                  0.55520   0.750
                                           4                  0.00000   0.889
                                           5                  0.05268   0.889
...                                                               ...     ...
2             1          1                 20                 0.00000   0.840
                                           21                 0.00000   0.840
                                           22                 0.00000   0.840
                                           23                 0.00000   0.840
                                           24                 0.00000   0.840

                                                              ttype  cups
atomic_number ion_charge level_index_lower level_index_upper
1             0          0                 1                      2   0.4
                                           2                      1   1.7
                                           3                      1   1.7
                                           4                      2   0.4
                                           5                      1   1.6
...                                                             ...   ...
2             1          1                 20                     2   2.0
                                           21                     2   1.9
                                           22                     2   1.9
                                           23                     2   1.9
                                           24                     2   1.9

[358 rows x 6 columns]